services:
  financeiro-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://financeiro-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    ports:
      - "${API_PORT}"
    networks:
      - "aspire"
  angular:
    image: "${ANGULAR_IMAGE}"
    environment:
      NODE_ENV: "production"
      API_HTTP: "http://api:${API_PORT}"
      services__api__http__0: "http://api:${API_PORT}"
      API_HTTPS: "https://api:${API_PORT}"
      PORT: "8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://financeiro-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "angular"
    ports:
      - "8000"
    depends_on:
      api:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
